#!/usr/bin/env python3
import argparse
import subprocess
import os
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--host-luajit", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--src-dir", required=True)
    parser.add_argument("--modules", nargs="+")
    args = parser.parse_args()

    with open(args.output, "w") as out:
        out.write("/* Automatically generated by gen_bundle.py */\n")
        out.write('#include "lua.h"\n')
        out.write('#include "lauxlib.h"\n\n')

        for mod_info in args.modules:
            file_path, mod_name, sym_name = mod_info.split(",")
            print(f"Bundling {mod_name} ({file_path})...")

            full_file_path = os.path.join(args.src_dir, file_path)

            # Apply patches if needed
            if mod_name == "cjson.util":
                print(f"Applying patch to {mod_name}...")
                with open(full_file_path, "r") as f:
                    content = f.read()

                # The patch from commit d94e160
                old_code = (
                    'print(("[%s] %s"):format(name, serialise_value(value, false)))'
                )
                new_code = """local val_str = serialise_value(value, false)
        if #val_str > 100 then
            val_str = val_str:sub(1, 100) .. "..."
        end
        print(("[%s] %s"):format(name, val_str))"""

                if old_code in content:
                    content = content.replace(old_code, new_code)
                    # Write to a temporary patched file
                    full_file_path = "tmp_patched.lua"
                    with open(full_file_path, "w") as f:
                        f.write(content)
                else:
                    print("Warning: Could not find code to patch in cjson.util")

            # Generate C bytecode
            # luajit -b -n <name> <input> <output>
            tmp_c = "tmp_bc.c"
            env = os.environ.copy()
            env["LUA_PATH"] = f"{args.src_dir}/src/?.lua;;"

            subprocess.run(
                [args.host_luajit, "-b", "-n", mod_name, full_file_path, tmp_c],
                env=env,
                check=True,
            )

            # Get size
            tmp_bin = "tmp_bc.bin"
            subprocess.run(
                [args.host_luajit, "-b", full_file_path, tmp_bin], env=env, check=True
            )
            size = os.path.getsize(tmp_bin)

            # Cleanup patched file if created
            if full_file_path == "tmp_patched.lua":
                os.remove(full_file_path)

            # Read and rename symbol in C file
            with open(tmp_c, "r") as f:
                c_content = f.read()

            # The symbol name generated by luajit -b -n mod_name is usually luaJIT_BC_mod_name
            # But dots are replaced by underscores.
            expected_sym = f"luaJIT_BC_{mod_name.replace('.', '_')}"
            target_sym = f"luaJIT_BC_{sym_name}"

            c_content = c_content.replace(expected_sym, target_sym)

            out.write(c_content)
            out.write(f"\nconst size_t {target_sym}_size = {size};\n\n")

            os.remove(tmp_c)
            os.remove(tmp_bin)


if __name__ == "__main__":
    main()
