/*
** Standalone LuaJIT interpreter with pre-loaded modules.
** Based on src/luajit.c.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define luajit_c

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "luajit.h"

#include "lj_arch.h"

#if LJ_TARGET_POSIX
#include <unistd.h>
#define lua_stdin_is_tty()	isatty(0)
#elif LJ_TARGET_WINDOWS
#include <io.h>
#ifdef __BORLANDC__
#define lua_stdin_is_tty()	isatty(_fileno(stdin))
#else
#define lua_stdin_is_tty()	_isatty(_fileno(stdin))
#endif
#else
#define lua_stdin_is_tty()	1
#endif

#if !LJ_TARGET_CONSOLE
#include <signal.h>

#if LJ_TARGET_POSIX
/* Improve signal handling on POSIX. Try CTRL-C on: luajit -e 'io.read()' */
static void signal_set(int sig, void (*h)(int))
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = h;
  sigemptyset(&sa.sa_mask);
  sigaction(sig, &sa, NULL);
}
#else
#define signal_set	signal
#endif

#endif

// External module declarations
int luaopen_lfs(lua_State *L);
int luaopen_cjson(lua_State *L);
int luaopen_cjson_safe(lua_State *L);
int luaopen_socket_core(lua_State *L);
int luaopen_mime_core(lua_State *L);

/* Bundled Lua bytecode declarations (generated during build) */
#define LUA_BUNDLE_DECL(sym) \
  extern const unsigned char luaJIT_BC_##sym[]; \
  extern const size_t luaJIT_BC_##sym##_size;

// We'll use explicit size variables generated by the build script
#define BUNDLE_BC(sym) luaJIT_BC_##sym
#define BUNDLE_SIZE(sym) luaJIT_BC_##sym##_size

extern const unsigned char luaJIT_BC_jit_bc[];
extern const size_t luaJIT_BC_jit_bc_size;
extern const unsigned char luaJIT_BC_jit_v[];
extern const size_t luaJIT_BC_jit_v_size;
extern const unsigned char luaJIT_BC_jit_dump[];
extern const size_t luaJIT_BC_jit_dump_size;
extern const unsigned char luaJIT_BC_jit_p[];
extern const size_t luaJIT_BC_jit_p_size;
extern const unsigned char luaJIT_BC_jit_zone[];
extern const size_t luaJIT_BC_jit_zone_size;
extern const unsigned char luaJIT_BC_jit_vmdef[];
extern const size_t luaJIT_BC_jit_vmdef_size;

#if defined(__aarch64__)
extern const unsigned char luaJIT_BC_jit_dis_arm64[];
extern const size_t luaJIT_BC_jit_dis_arm64_size;
#elif defined(__arm__)
extern const unsigned char luaJIT_BC_jit_dis_arm[];
extern const size_t luaJIT_BC_jit_dis_arm_size;
#elif defined(__x86_64__)
extern const unsigned char luaJIT_BC_jit_dis_x64[];
extern const size_t luaJIT_BC_jit_dis_x64_size;
extern const unsigned char luaJIT_BC_jit_dis_x86[];
extern const size_t luaJIT_BC_jit_dis_x86_size;
#endif

extern const unsigned char luaJIT_BC_socket[];
extern const size_t luaJIT_BC_socket_size;
extern const unsigned char luaJIT_BC_mime[];
extern const size_t luaJIT_BC_mime_size;
extern const unsigned char luaJIT_BC_ltn12[];
extern const size_t luaJIT_BC_ltn12_size;
extern const unsigned char luaJIT_BC_socket_http[];
extern const size_t luaJIT_BC_socket_http_size;
extern const unsigned char luaJIT_BC_socket_tp[];
extern const size_t luaJIT_BC_socket_tp_size;
extern const unsigned char luaJIT_BC_socket_ftp[];
extern const size_t luaJIT_BC_socket_ftp_size;
extern const unsigned char luaJIT_BC_socket_smtp[];
extern const size_t luaJIT_BC_socket_smtp_size;
extern const unsigned char luaJIT_BC_socket_url[];
extern const size_t luaJIT_BC_socket_url_size;
extern const unsigned char luaJIT_BC_socket_headers[];
extern const size_t luaJIT_BC_socket_headers_size;
extern const unsigned char luaJIT_BC_socket_mbox[];
extern const size_t luaJIT_BC_socket_mbox_size;

extern const unsigned char luaJIT_BC_cjson_util[];
extern const size_t luaJIT_BC_cjson_util_size;

/* Helper to load bundled bytecode */
static int load_bundled_bc(lua_State *L) {
    const unsigned char *bc = (const unsigned char *)lua_touserdata(L, lua_upvalueindex(1));
    size_t size = (size_t)lua_tonumber(L, lua_upvalueindex(2));
    const char *name = lua_tostring(L, lua_upvalueindex(3));
    if (luaL_loadbuffer(L, (const char *)bc, size, name)) {
        return lua_error(L);
    }
    lua_pushvalue(L, 1); /* Pass the module name to the chunk */
    lua_call(L, 1, 1);
    return 1;
}

static void register_bundle(lua_State *L, const char *name, const unsigned char *bc, size_t size) {
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");
    lua_pushlightuserdata(L, (void *)bc);
    lua_pushnumber(L, (double)size);
    lua_pushstring(L, name);
    lua_pushcclosure(L, load_bundled_bc, 3);
    lua_setfield(L, -2, name);
    lua_pop(L, 2);
}

static void preload_modules(lua_State *L) {
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");

    lua_pushcfunction(L, luaopen_lfs);
    lua_setfield(L, -2, "lfs");

    lua_pushcfunction(L, luaopen_cjson);
    lua_setfield(L, -2, "cjson");

    lua_pushcfunction(L, luaopen_cjson_safe);
    lua_setfield(L, -2, "cjson.safe");

    lua_pushcfunction(L, luaopen_socket_core);
    lua_setfield(L, -2, "socket.core");

    lua_pushcfunction(L, luaopen_mime_core);
    lua_setfield(L, -2, "mime.core");

    lua_pop(L, 2);

    /* Pre-load Lua modules */
    register_bundle(L, "jit.bc", BUNDLE_BC(jit_bc), BUNDLE_SIZE(jit_bc));
    register_bundle(L, "jit.v", BUNDLE_BC(jit_v), BUNDLE_SIZE(jit_v));
    register_bundle(L, "jit.dump", BUNDLE_BC(jit_dump), BUNDLE_SIZE(jit_dump));
    register_bundle(L, "jit.p", BUNDLE_BC(jit_p), BUNDLE_SIZE(jit_p));
    register_bundle(L, "jit.zone", BUNDLE_BC(jit_zone), BUNDLE_SIZE(jit_zone));
    register_bundle(L, "jit.vmdef", BUNDLE_BC(jit_vmdef), BUNDLE_SIZE(jit_vmdef));

#if defined(__aarch64__)
    register_bundle(L, "jit.dis_arm64", BUNDLE_BC(jit_dis_arm64), BUNDLE_SIZE(jit_dis_arm64));
#elif defined(__arm__)
    register_bundle(L, "jit.dis_arm", BUNDLE_BC(jit_dis_arm), BUNDLE_SIZE(jit_dis_arm));
#elif defined(__x86_64__)
    register_bundle(L, "jit.dis_x64", BUNDLE_BC(jit_dis_x64), BUNDLE_SIZE(jit_dis_x64));
    register_bundle(L, "jit.dis_x86", BUNDLE_BC(jit_dis_x86), BUNDLE_SIZE(jit_dis_x86));
#endif

    register_bundle(L, "socket", BUNDLE_BC(socket), BUNDLE_SIZE(socket));
    register_bundle(L, "mime", BUNDLE_BC(mime), BUNDLE_SIZE(mime));
    register_bundle(L, "ltn12", BUNDLE_BC(ltn12), BUNDLE_SIZE(ltn12));
    register_bundle(L, "socket.http", BUNDLE_BC(socket_http), BUNDLE_SIZE(socket_http));
    register_bundle(L, "socket.tp", BUNDLE_BC(socket_tp), BUNDLE_SIZE(socket_tp));
    register_bundle(L, "socket.ftp", BUNDLE_BC(socket_ftp), BUNDLE_SIZE(socket_ftp));
    register_bundle(L, "socket.smtp", BUNDLE_BC(socket_smtp), BUNDLE_SIZE(socket_smtp));
    register_bundle(L, "socket.url", BUNDLE_BC(socket_url), BUNDLE_SIZE(socket_url));
    register_bundle(L, "socket.headers", BUNDLE_BC(socket_headers), BUNDLE_SIZE(socket_headers));
    register_bundle(L, "socket.mbox", BUNDLE_BC(socket_mbox), BUNDLE_SIZE(socket_mbox));

    register_bundle(L, "cjson.util", BUNDLE_BC(cjson_util), BUNDLE_SIZE(cjson_util));
}

static lua_State *globalL = NULL;
static const char *progname = LUA_PROGNAME;
static char *empty_argv[2] = { NULL, NULL };

#if !LJ_TARGET_CONSOLE
static void lstop(lua_State *L, lua_Debug *ar)
{
  (void)ar;  /* unused arg. */
  lua_sethook(L, NULL, 0, 0);
  /* Avoid luaL_error -- a C hook doesn't add an extra frame. */
  luaL_where(L, 0);
  lua_pushfstring(L, "%sinterrupted!", lua_tostring(L, -1));
  lua_error(L);
}

static void laction(int i)
{
  /* Terminate process if another SIGINT happens (double CTRL-C). */
  signal_set(i, SIG_DFL);
  lua_sethook(globalL, lstop, LUA_MASKCALL | LUA_MASKRET | LUA_MASKCOUNT, 1);
}
#endif

static void print_usage(void)
{
  fputs("usage: ", stderr);
  fputs(progname, stderr);
  fputs(" [options]... [script [args]...].\n"
  "Available options are:\n"
  "  -e chunk  Execute string " LUA_QL("chunk") ".\n"
  "  -l name   Require library " LUA_QL("name") ".\n"
  "  -b ...    Save or list bytecode.\n"
  "  -j cmd    Perform LuaJIT control command.\n"
  "  -O[opt]   Control LuaJIT optimizations.\n"
  "  -i        Enter interactive mode after executing " LUA_QL("script") ".\n"
  "  -v        Show version information.\n"
  "  -m        Print supported modules.\n"
  "  -E        Ignore environment variables.\n"
  "  --        Stop handling options.\n"
  "  -         Execute stdin and stop handling options.\n", stderr);
  fflush(stderr);
}

static void l_message(const char *msg)
{
  if (progname) { fputs(progname, stderr); fputc(':', stderr); fputc(' ', stderr); }
  fputs(msg, stderr); fputc('\n', stderr);
  fflush(stderr);
}

static int report(lua_State *L, int status)
{
  if (status && !lua_isnil(L, -1)) {
    const char *msg = lua_tostring(L, -1);
    if (msg == NULL) msg = "(error object is not a string)";
    l_message(msg);
    lua_pop(L, 1);
  }
  return status;
}

static int traceback(lua_State *L)
{
  if (!lua_isstring(L, 1)) { /* Non-string error object? Try metamethod. */
    if (lua_isnoneornil(L, 1) ||
	!luaL_callmeta(L, 1, "__tostring") ||
	!lua_isstring(L, -1))
      return 1;  /* Return non-string error object. */
    lua_remove(L, 1);  /* Replace object by result of __tostring metamethod. */
  }
  luaL_traceback(L, L, lua_tostring(L, 1), 1);
  return 1;
}

static int docall(lua_State *L, int narg, int clear)
{
  int status;
  int base = lua_gettop(L) - narg;  /* function index */
  lua_pushcfunction(L, traceback);  /* push traceback function */
  lua_insert(L, base);  /* put it under chunk and args */
#if !LJ_TARGET_CONSOLE
  signal_set(SIGINT, laction);
#endif
  status = lua_pcall(L, narg, (clear ? 0 : LUA_MULTRET), base);
#if !LJ_TARGET_CONSOLE
  signal_set(SIGINT, SIG_DFL);
#endif
  lua_remove(L, base);  /* remove traceback function */
  /* force a complete garbage collection in case of errors */
  if (status != LUA_OK) lua_gc(L, LUA_GCCOLLECT, 0);
  return status;
}

static void print_version(void)
{
  fputs(LUAJIT_VERSION " -- " LUAJIT_COPYRIGHT ". " LUAJIT_URL "\n", stdout);
}

static void print_supported_modules(lua_State *L)
{
  printf("Standard modules:\n");
  printf("  base, bit, debug, ffi, io, jit, math, os, package, string, table\n\n");
  printf("Bundled modules:\n");
  lua_getglobal(L, "package");
  lua_getfield(L, -1, "preload");
  lua_pushnil(L);
  while (lua_next(L, -2) != 0) {
    if (lua_isstring(L, -2)) {
      printf("  %s\n", lua_tostring(L, -2));
    }
    lua_pop(L, 1);
  }
  lua_pop(L, 2);
}

static void print_jit_status(lua_State *L)
{
  int n;
  const char *s;
  lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_getfield(L, -1, "jit");  /* Get jit.* module table. */
  lua_remove(L, -2);
  lua_getfield(L, -1, "status");
  lua_remove(L, -2);
  n = lua_gettop(L);
  lua_call(L, 0, LUA_MULTRET);
  fputs(lua_toboolean(L, n) ? "JIT: ON" : "JIT: OFF", stdout);
  for (n++; (s = lua_tostring(L, n)); n++) {
    putc(' ', stdout);
    fputs(s, stdout);
  }
  putc('\n', stdout);
  lua_settop(L, 0);  /* clear stack */
}

static void createargtable(lua_State *L, char **argv, int argc, int argf)
{
  int i;
  lua_createtable(L, argc - argf, argf);
  for (i = 0; i < argc; i++) {
    lua_pushstring(L, argv[i]);
    lua_rawseti(L, -2, i - argf);
  }
  lua_setglobal(L, "arg");
}

static int dofile(lua_State *L, const char *name)
{
  int status = luaL_loadfile(L, name) || docall(L, 0, 1);
  return report(L, status);
}

static int dostring(lua_State *L, const char *s, const char *name)
{
  int status = luaL_loadbuffer(L, s, strlen(s), name) || docall(L, 0, 1);
  return report(L, status);
}

static int dolibrary(lua_State *L, const char *name)
{
  lua_getglobal(L, "require");
  lua_pushstring(L, name);
  return report(L, docall(L, 1, 1));
}

static void write_prompt(lua_State *L, int firstline)
{
  const char *p;
  lua_getfield(L, LUA_GLOBALSINDEX, firstline ? "_PROMPT" : "_PROMPT2");
  p = lua_tostring(L, -1);
  if (p == NULL) p = firstline ? LUA_PROMPT : LUA_PROMPT2;
  fputs(p, stdout);
  fflush(stdout);
  lua_pop(L, 1);  /* remove global */
}

static int incomplete(lua_State *L, int status)
{
  if (status == LUA_ERRSYNTAX) {
    size_t lmsg;
    const char *msg = lua_tolstring(L, -1, &lmsg);
    const char *tp = msg + lmsg - (sizeof(LUA_QL("<eof>")) - 1);
    if (strstr(msg, LUA_QL("<eof>")) == tp) {
      lua_pop(L, 1);
      return 1;
    }
  }
  return 0;  /* else... */
}

static int pushline(lua_State *L, int firstline)
{
  char buf[LUA_MAXINPUT];
  write_prompt(L, firstline);
  if (fgets(buf, LUA_MAXINPUT, stdin)) {
    size_t len = strlen(buf);
    if (len > 0 && buf[len-1] == '\n')
      buf[len-1] = '\0';
    if (firstline && buf[0] == '=')
      lua_pushfstring(L, "return %s", buf+1);
    else
      lua_pushstring(L, buf);
    return 1;
  }
  return 0;
}

static int loadline(lua_State *L)
{
  int status;
  lua_settop(L, 0);
  if (!pushline(L, 1))
    return -1;  /* no input */
  for (;;) {  /* repeat until gets a complete line */
    status = luaL_loadbuffer(L, lua_tostring(L, 1), lua_strlen(L, 1), "=stdin");
    if (!incomplete(L, status)) break;  /* cannot try to add lines? */
    if (!pushline(L, 0))  /* no more input? */
      return -1;
    lua_pushliteral(L, "\n");  /* add a new line... */
    lua_insert(L, -2);  /* ...between the two lines */
    lua_concat(L, 3);  /* join them */
  }
  lua_remove(L, 1);  /* remove line */
  return status;
}

static void dotty(lua_State *L)
{
  int status;
  const char *oldprogname = progname;
  progname = NULL;
  while ((status = loadline(L)) != -1) {
    if (status == LUA_OK) status = docall(L, 0, 0);
    report(L, status);
    if (status == LUA_OK && lua_gettop(L) > 0) {  /* any result to print? */
      lua_getglobal(L, "print");
      lua_insert(L, 1);
      if (lua_pcall(L, lua_gettop(L)-1, 0, 0) != 0)
	l_message(lua_pushfstring(L, "error calling " LUA_QL("print") " (%s)",
				  lua_tostring(L, -1)));
    }
  }
  lua_settop(L, 0);  /* clear stack */
  fputs("\n", stdout);
  fflush(stdout);
  progname = oldprogname;
}

static int handle_script(lua_State *L, char **argx)
{
  int status;
  const char *fname = argx[0];
  if (strcmp(fname, "-") == 0 && strcmp(argx[-1], "--") != 0)
    fname = NULL;  /* stdin */
  status = luaL_loadfile(L, fname);
  if (status == LUA_OK) {
    /* Fetch args from arg table. LUA_INIT or -e might have changed them. */
    int narg = 0;
    lua_getglobal(L, "arg");
    if (lua_istable(L, -1)) {
      do {
	narg++;
	lua_rawgeti(L, -narg, narg);
      } while (!lua_isnil(L, -1));
      lua_pop(L, 1);
      lua_remove(L, -narg);
      narg--;
    } else {
      lua_pop(L, 1);
    }
    status = docall(L, narg, 0);
  }
  return report(L, status);
}

/* Load add-on module. */
static int loadjitmodule(lua_State *L)
{
  lua_getglobal(L, "require");
  lua_pushliteral(L, "jit.");
  lua_pushvalue(L, -3);
  lua_concat(L, 2);
  if (lua_pcall(L, 1, 1, 0)) {
    const char *msg = lua_tostring(L, -1);
    if (msg && !strncmp(msg, "module ", 7))
      goto nomodule;
    return report(L, 1);
  }
  lua_getfield(L, -1, "start");
  if (lua_isnil(L, -1)) {
  nomodule:
    l_message("unknown luaJIT command or jit.* modules not installed");
    return 1;
  }
  lua_remove(L, -2);  /* Drop module table. */
  return 0;
}

/* Run command with options. */
static int runcmdopt(lua_State *L, const char *opt)
{
  int narg = 0;
  if (opt && *opt) {
    for (;;) {  /* Split arguments. */
      const char *p = strchr(opt, ',');
      narg++;
      if (!p) break;
      if (p == opt)
	lua_pushnil(L);
      else
	lua_pushlstring(L, opt, (size_t)(p - opt));
      opt = p + 1;
    }
    if (*opt)
      lua_pushstring(L, opt);
    else
      lua_pushnil(L);
  }
  return report(L, lua_pcall(L, narg, 0, 0));
}

/* JIT engine control command: try jit library first or load add-on module. */
static int dojitcmd(lua_State *L, const char *cmd)
{
  const char *opt = strchr(cmd, '=');
  lua_pushlstring(L, cmd, opt ? (size_t)(opt - cmd) : strlen(cmd));
  lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_getfield(L, -1, "jit");  /* Get jit.* module table. */
  lua_remove(L, -2);
  lua_pushvalue(L, -2);
  lua_gettable(L, -2);  /* Lookup library function. */
  if (!lua_isfunction(L, -1)) {
    lua_pop(L, 2);  /* Drop non-function and jit.* table, keep module name. */
    if (loadjitmodule(L))
      return 1;
  } else {
    lua_remove(L, -2);  /* Drop jit.* table. */
  }
  lua_remove(L, -2);  /* Drop module name. */
  return runcmdopt(L, opt ? opt+1 : opt);
}

/* Optimization flags. */
static int dojitopt(lua_State *L, const char *opt)
{
  lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
  lua_getfield(L, -1, "jit.opt");  /* Get jit.opt.* module table. */
  lua_remove(L, -2);
  lua_getfield(L, -1, "start");
  lua_remove(L, -2);
  return runcmdopt(L, opt);
}

/* Save or list bytecode. */
static int dobytecode(lua_State *L, char **argv)
{
  int narg = 0;
  lua_pushliteral(L, "bcsave");
  if (loadjitmodule(L))
    return 1;
  if (argv[0][2]) {
    narg++;
    argv[0][1] = '-';
    lua_pushstring(L, argv[0]+1);
  }
  for (argv++; *argv != NULL; narg++, argv++)
    lua_pushstring(L, *argv);
  report(L, lua_pcall(L, narg, 0, 0));
  return -1;
}

/* check that argument has no extra characters at the end */
#define notail(x)	{if ((x)[2] != '\0') return -1;}

#define FLAGS_INTERACTIVE	1
#define FLAGS_VERSION		2
#define FLAGS_EXEC		4
#define FLAGS_OPTION		8
#define FLAGS_NOENV		16
#define FLAGS_LIST_MODS		32

static int collectargs(char **argv, int *flags)
{
  int i;
  for (i = 1; argv[i] != NULL; i++) {
    if (argv[i][0] != '-')  /* Not an option? */
      return i;
    switch (argv[i][1]) {  /* Check option. */
    case '-':
      notail(argv[i]);
      return i+1;
    case '\0':
      return i;
    case 'i':
      notail(argv[i]);
      *flags |= FLAGS_INTERACTIVE;
      /* fallthrough */
    case 'v':
      notail(argv[i]);
      *flags |= FLAGS_VERSION;
      break;
    case 'm':
      notail(argv[i]);
      *flags |= FLAGS_LIST_MODS;
      break;
    case 'e':
      *flags |= FLAGS_EXEC;
      /* fallthrough */
    case 'j':  /* LuaJIT extension */
    case 'l':
      *flags |= FLAGS_OPTION;
      if (argv[i][2] == '\0') {
	i++;
	if (argv[i] == NULL) return -1;
      }
      break;
    case 'O': break;  /* LuaJIT extension */
    case 'b':  /* LuaJIT extension */
      if (*flags) return -1;
      *flags |= FLAGS_EXEC;
      return i+1;
    case 'E':
      *flags |= FLAGS_NOENV;
      break;
    default: return -1;  /* invalid option */
    }
  }
  return i;
}

static int runargs(lua_State *L, char **argv, int argn)
{
  int i;
  for (i = 1; i < argn; i++) {
    if (argv[i] == NULL) continue;
    lua_assert(argv[i][0] == '-');
    switch (argv[i][1]) {
    case 'e': {
      const char *chunk = argv[i] + 2;
      if (*chunk == '\0') chunk = argv[++i];
      lua_assert(chunk != NULL);
      if (dostring(L, chunk, "=(command line)") != 0)
	return 1;
      break;
      }
    case 'l': {
      const char *filename = argv[i] + 2;
      if (*filename == '\0') filename = argv[++i];
      lua_assert(filename != NULL);
      if (dolibrary(L, filename))
	return 1;
      break;
      }
    case 'j': {  /* LuaJIT extension. */
      const char *cmd = argv[i] + 2;
      if (*cmd == '\0') cmd = argv[++i];
      lua_assert(cmd != NULL);
      if (dojitcmd(L, cmd))
	return 1;
      break;
      }
    case 'O':  /* LuaJIT extension. */
      if (dojitopt(L, argv[i] + 2))
	return 1;
      break;
    case 'b':  /* LuaJIT extension. */
      return dobytecode(L, argv+i);
    default: break;
    }
  }
  return LUA_OK;
}

static int handle_luainit(lua_State *L)
{
#if LJ_TARGET_CONSOLE
  const char *init = NULL;
#else
  const char *init = getenv(LUA_INIT);
#endif
  if (init == NULL)
    return LUA_OK;
  else if (init[0] == '@')
    return dofile(L, init+1);
  else
    return dostring(L, init, "=" LUA_INIT);
}

static struct Smain {
  char **argv;
  int argc;
  int status;
} smain;

static int pmain(lua_State *L)
{
  struct Smain *s = &smain;
  char **argv = s->argv;
  int argn;
  int flags = 0;
  globalL = L;
  LUAJIT_VERSION_SYM();  /* Linker-enforced version check. */

  argn = collectargs(argv, &flags);
  if (argn < 0) {  /* Invalid args? */
    print_usage();
    s->status = 1;
    return 0;
  }

  if ((flags & FLAGS_NOENV)) {
    lua_pushboolean(L, 1);
    lua_setfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
  }

  /* Stop collector during library initialization. */
  lua_gc(L, LUA_GCSTOP, 0);
  luaL_openlibs(L);
  preload_modules(L);
  lua_gc(L, LUA_GCRESTART, -1);

  createargtable(L, argv, s->argc, argn);

  if (!(flags & FLAGS_NOENV)) {
    s->status = handle_luainit(L);
    if (s->status != LUA_OK) return 0;
  }

  if ((flags & FLAGS_VERSION)) print_version();
  if ((flags & FLAGS_LIST_MODS)) print_supported_modules(L);

  s->status = runargs(L, argv, argn);
  if (s->status != LUA_OK) return 0;

  if (s->argc > argn) {
    s->status = handle_script(L, argv + argn);
    if (s->status != LUA_OK) return 0;
  }

  if ((flags & FLAGS_INTERACTIVE)) {
    print_jit_status(L);
    dotty(L);
  } else if (s->argc == argn && !(flags & (FLAGS_EXEC|FLAGS_VERSION|FLAGS_LIST_MODS))) {
    if (lua_stdin_is_tty()) {
      print_version();
      print_jit_status(L);
      dotty(L);
    } else {
      dofile(L, NULL);  /* Executes stdin as a file. */
    }
  }
  return 0;
}

int main(int argc, char **argv)
{
  int status;
  lua_State *L;
  if (!argv[0]) argv = empty_argv; else if (argv[0][0]) progname = argv[0];
  L = lua_open();
  if (L == NULL) {
    l_message("cannot create state: not enough memory");
    return EXIT_FAILURE;
  }
  smain.argc = argc;
  smain.argv = argv;
  status = lua_cpcall(L, pmain, NULL);
  report(L, status);
  lua_close(L);
  return (status || smain.status > 0) ? EXIT_FAILURE : EXIT_SUCCESS;
}
